# Meta
site_name: VulkanTutorialCN
site_description: Vulkan 中文教程，旨在为广大 Vulkan 爱好者提供 Vulkan 教程的中文支持、改善学习体验、扩大 Vulkan 在国内的影响力。
site_author: VulkanTutorialCN
copyright: ©2021-2021 Copyright VulkanTutorialCN Team

# Theme
theme:
  name: material

# GitHub
repo_url: https://github.com/VulkanTutorialCN/VulkanTutorialCN
repo_name: VulkanTutorialCN
