# Meta
site_name: VulkanTutorialCN
site_description: Vulkan 中文教程，旨在为广大 Vulkan 爱好者提供 Vulkan 教程的中文支持、改善学习体验、扩大 Vulkan 在国内的影响力。
site_author: VulkanTutorialCN
copyright: ©2021-2021 Copyright VulkanTutorialCN Team

# Theme
theme:
  name: material

# GitHub
repo_url: https://github.com/VulkanTutorialCN/VulkanTutorialCN
repo_name: VulkanTutorialCN

# Navs
nav:
  - '序言': 'index.md'
  - '介绍': '00-introduction.md'
  - '概览': '01-overview.md'
  - '开发环境配置': '02-development-environment.md'
  - '第一个三角形':
    - '初始化':
      - '基础代码': '03-drawing-a-triangle/03-01-setup/03-01-01-base-code.md'
